package strategy

import (
	"errors"
	"time"

	"final-bot-trader-api/internal/exchange/model"
	"final-bot-trader-api/internal/indicator"
)

// Common errors
var (
	ErrInsufficientData   = errors.New("insufficient data for analysis")
	ErrNoSignal           = errors.New("no trading signal generated")
	ErrInvalidParameters  = errors.New("invalid strategy parameters")
	ErrStrategyNotReady   = errors.New("strategy not ready for trading")
)

// SignalType represents the type of trading signal
type SignalType int

const (
	SignalNone SignalType = iota
	SignalBuy             // Open long position
	SignalSell            // Open short position
	SignalCloseLong       // Close long position
	SignalCloseShort      // Close short position
)

func (s SignalType) String() string {
	switch s {
	case SignalBuy:
		return "BUY"
	case SignalSell:
		return "SELL"
	case SignalCloseLong:
		return "CLOSE_LONG"
	case SignalCloseShort:
		return "CLOSE_SHORT"
	default:
		return "NONE"
	}
}

// Signal represents a trading signal generated by a strategy
type Signal struct {
	Type       SignalType
	Symbol     string
	Price      float64   // Suggested entry price
	Quantity   float64   // Suggested quantity
	TP         float64   // Take profit price
	SL         float64   // Stop loss price
	Confidence float64   // Confidence level (0-1)
	Reason     string    // Human-readable reason for the signal
	Timestamp  time.Time // When the signal was generated
	Indicators map[string]float64 // Indicator values that generated the signal
}

// Strategy is the interface that all trading strategies must implement
type Strategy interface {
	// Name returns the name of the strategy
	Name() string

	// Description returns a description of the strategy
	Description() string

	// Analyze analyzes the candles and returns a trading signal
	Analyze(candles []model.Candle) (*Signal, error)

	// MinimumCandles returns the minimum number of candles required
	MinimumCandles() int

	// Parameters returns the current strategy parameters
	Parameters() map[string]interface{}

	// SetParameters updates the strategy parameters
	SetParameters(params map[string]interface{}) error
}

// BaseStrategy provides common functionality for strategies
type BaseStrategy struct {
	symbol string
}

// NewBaseStrategy creates a new base strategy
func NewBaseStrategy(symbol string) BaseStrategy {
	return BaseStrategy{symbol: symbol}
}

// Symbol returns the trading symbol
func (b *BaseStrategy) Symbol() string {
	return b.symbol
}

// CreateSignal is a helper to create a signal with common fields
func (b *BaseStrategy) CreateSignal(signalType SignalType, price float64, reason string) *Signal {
	return &Signal{
		Type:       signalType,
		Symbol:     b.symbol,
		Price:      price,
		Confidence: 0.5, // Default confidence
		Reason:     reason,
		Timestamp:  time.Now(),
		Indicators: make(map[string]float64),
	}
}

// IndicatorToStrategySignal converts indicator signal to strategy signal
func IndicatorToStrategySignal(indSignal indicator.SignalType) SignalType {
	switch indSignal {
	case indicator.SignalBuy:
		return SignalBuy
	case indicator.SignalSell:
		return SignalSell
	default:
		return SignalNone
	}
}
